live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[cursor]
style = { shape = "Block", blinking = "Never" }
vi_mode_style = { shape = "Block", blinking = "Never" }
unfocused_hollow = true

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 19.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.offset]
x = 0
y = 6

[font.glyph_offset]
x = 0
y = 3

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[mouse]
hide_when_typing = true

[scrolling]
history = 2000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
opacity = 1.0
startup_mode = "windowed"
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[colors]
draw_bold_text_with_bright_colors = false

# Mountain theme
# [colors.primary]
# background = "0x0f0f0f"
# foreground = "0xf0f0f0"
#
# [colors.normal]
# black = "0x262626"
# red = "0xac8a8c"
# green = "0x8aac8b"
# yellow = "0xaca98a"
# blue = "0x8f8aac"
# magenta = "0xac8aac"
# cyan = "0x8aabac"
# white = "0xe7e7e7"
#
# [colors.bright]
# black = "0x4c4c4c"
# red = "0xc49ea0"
# green = "0x9ec49f"
# yellow = "0xc4c19e"
# blue = "0xa39ec4"
# magenta = "0xc49ec4"
# cyan = "0x9ec3c4"
# white = "0xf5f5f5"

# Catppuccin theme
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
