If:
  PathMatch: .*\.cpp
CompileFlags: 
  Add: [-xc++, -Wall, -std=c++20]
  Compiler: clang++ 
---
If:
  PathMatch: .*\.c
CompileFlags:
  Add: [-xc, -Wall, -std=c17]
  Compiler: clang++
---
Index:
  Background: Build

Hover:
  ShowAKA: Yes

InlayHints:
  BlockEnd: No
  Designators: Yes 
  Enabled: Yes 
  ParameterNames: Yes 
  DeducedTypes: Yes

Diagnostics:
  UnusedIncludes: Strict
