"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

add_newline = false # disable multiline prompt

format = '''
[   ](fg:dir_fg_icon bg:dir_bg)$directory
'''

right_format = '''
$git_branch
'''

# Mountain theme
# [palettes.colors]
# dir_fg_icon = "#8e8aa9"
# dir_fg = "#a38c8c"
# dir_bg = "#171717"
# dir_2 = "#151515"
# dir_3 = "#131313"
# dir_4 = "#111111"

# Catppuccin theme
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
# ---
dir_fg_icon = "#b4befe"
dir_fg = "#f2cdcd"
dir_bg = "#2D2D45"
dir_2 = "#292940"
dir_3 = "#26263B"
dir_4 = "#232336"

[directory]
truncation_length = 2
style = "fg:dir_fg bg:dir_bg"
format = "[$path ]($style)[ ](bg:dir_2)[ ](bg:dir_3)[ ](bg:dir_4)"

[git_branch]
style = "fg:dir_fg bg:dir_bg"
format = "[ ](bg:dir_4)[ ](bg:dir_3)[ ](bg:dir_2)[ $branch]($style)[   ](fg:dir_fg_icon bg:dir_bg)"
