"$schema" = 'https://starship.rs/config-schema.json'

palette = "colors"

add_newline = false # disable multiline prompt

format = '''
[   ](fg:dir_fg_icon bg:dir_bg)$directory
'''

right_format = '''
$git_branch
'''

[palettes.colors]
dir_fg_icon = "#8e8aa9"
dir_fg = "#a38c8c"
dir_bg = "#171717"
dir_2 = "#151515"
dir_3 = "#131313"
dir_4 = "#111111"

[directory]
truncation_length = 2
style = "fg:dir_fg bg:dir_bg"
format = "[$path ]($style)[ ](bg:dir_2)[ ](bg:dir_3)[ ](bg:dir_4)"

[git_branch]
style = "fg:dir_fg bg:dir_bg"
format = "[ ](bg:dir_4)[ ](bg:dir_3)[ ](bg:dir_2)[ $branch]($style)[   ](fg:dir_fg_icon bg:dir_bg)"
