If:
  PathMatch: .*\.cpp
CompileFlags:
  Add: [-xc++, -Wall, -std=c++20]
  Compiler: clang++
---
If:
  PathMatch: .*\.c
CompileFlags:
  Add: [-xc, -Wall, -std=c17]
  Compiler: clang
---
Index:
  Background: Build

Hover:
  ShowAKA: true

InlayHints:
  BlockEnd: false
  Designators: true
  Enabled: false
  ParameterNames: true
  DeducedTypes: true

Diagnostics:
  UnusedIncludes: Strict
