If:
  PathMatch: .*\.cpp
CompileFlags:
  Add: [-xc++, -Wall, -std=c++23]
  Compiler: clang++
---
If:
  PathMatch: .*\.c
CompileFlags:
  Add: [-xc, -Wall, -std=c23]
  Compiler: clang
---
Index:
  Background: Build

Hover:
  ShowAKA: true

InlayHints:
  BlockEnd: true
  Designators: true
  Enabled: true
  ParameterNames: true
  DeducedTypes: true

Diagnostics:
  UnusedIncludes: Strict
